name: CI

on:
  push:
    branches: [main]
    workflow_dispatch
    
jobs:

  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, World!!"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Multi-line bash
        run: |
          echo "I will fail"
          exit 1

      - name: Say goodbie
        run: echo "Goodbye!"