name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use pnpm 10.19.0
        uses: pnpm/action-setup@v4
        with:
          version: 10.19.0
          run_install: false

      - name: Use Node.js 24.11.0
        uses: actions/setup-node@v4
        with:
          node-version: 24.11.0
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm format

      - name: Lint
        run: pnpm lint

      - name: Unit tests
        run: echo "pnpm test"

      - name: E2E tests
        run: echo "pnpm test:e2e"

      - name: Audit
        run: pnpm audit

      - name: Build
        run: pnpm build
